### ISSUE TITLE
Help with Quantizing in bin/background2vxp.py

### ISSUE THREAD

**Issue by davidrenne** [foone/7gen#3]
I wrote a little script to take a JPEG and convert to a BMP in the sizes you specified in background2vxp.py:

```
from PIL import Image
fname = 'forest-g7aa59715e_1920'
name='Cartoon Forest'
shortname=name.lower().replace(" ", "_") # out file will be shortname with a 'vxp' extension
img = Image.open("images/" + fname + ".jpeg")
img = img.resize((544, 306), Image.ANTIALIAS)
bgFname = "images/" + fname + ".bmp"
img.save(bgFname)

bgFnamePreview = "images/" + fname + "-preview.bmp"
img = img.resize((128, 72), Image.ANTIALIAS)
img.save(bgFnamePreview)
```

It output these two files during the resize and conversion to be used in background2vxp.py:

[Forest](https://imgur.com/wK2K6w1)

[Forest Preview](https://imgur.com/XWK1L5h)

[Original File Used To Convert To BMP](https://pixabay.com/illustrations/forest-trees-fog-silhouette-mist-5855196/)

But I tried this two times on two different files from thsi pixabay site and in both cases I got this stacktrace:

```
Traceback (most recent call last):
  File "bin/background2vxp.py", line 239, in <module>
    CreateBackgroundFromImages(name,author,outfile,shortname,background,depth,preview,dither,uniqueid,NullProgress)
  File "bin/background2vxp.py", line 196, in CreateBackgroundFromImages
    minisurf=GetTexture(preview)
  File "bin/background2vxp.py", line 174, in GetTexture
    raise SaveError('Quantizing image failed!')
error.SaveError: 'Quantizing image failed!'
```

Can you help me understand how to prepare JPEGs to BMPs that will allow it to Quantize?

Thanks @foone and thanks again for open sourcing 3DMM with Microsoft.  

Theres only [49 scenes](https://3dmm.com/mods.php?do=filter&field=1&select=3) on 3dmm.com and I want to expand these massively so I need to know how to properly convert JPEGS to 3dmm backgrounds.

**Comment by davidrenne** [comment]
@foone I am on a mac.  Should I try on windows or linux the same script?

**Comment by davidrenne** [comment]
LOL @foone  I am noticing that inside my QuantizeImage def it cant import the quantizer2 package which is in the code/ folder which calls filename='Quanter2.exe' so this definitely needs to be run on windows and not a mac to quantize that at the shell level.

I think I figured out my problems and Ill setup a windows environment for my scripts to create more image based scenes cause I hate the 3dmm.com ones people have generated.

**Comment by davidrenne** [comment]
Got [250 new scenes](https://www.youtube.com/watch?v=MQCfPrhRrRs) [done on my fork](https://github.com/foone/7gen/commit/54ac6304f7b617bfc73d6556fd81c58dcbefa0d6) tonight and 2000 more images to sift through what could make good looking scenes.

I think they look great and will be great to use with my kid making movies.  Way better than what has been published so far on 3dmm.com
